export const items = [
    {name: 'product 1', category: 'Bag'},
    {name: 'product 2', category: 'Watch'},
    {name: 'product 3', category: 'Camera'},
    {name: 'product 4', category: 'Bags'},
    {name: 'product 5', category: 'Bags'},
    {name: 'product 6', category: 'Camera'},
    {name: 'product 7', category: 'Watch'},
    {name: 'product 8', category: 'Electronics'},
    {name: 'product 9', category: 'Bags'},
    {name: 'product 10', category: 'Electronics'},
    {name: 'product 11', category: 'Watch'},
    {name: 'product 12', category: 'Camera'},
    {name: 'product 13', category: 'Electronics'},
    {name: 'product 14', category: 'Electronics'},
    {name: 'product 15', category: 'Watch'},
]