export const items = [
    {name: 'safari', category: 'Bag'},
    {name: 'sonata', category: 'Watch'},
    {name: 'Nikon', category: 'Camera'},
    {name: 'American Tourister', category: 'Bags'},
    {name: 'Skybags', category: 'Bags'},
    {name: 'Sony', category: 'Camera'},
    {name: 'sonata', category: 'Watch'},
    {name: 'LG', category: 'Electronics'},
    {name: 'Safari', category: 'Bags'},
    {name: 'sony', category: 'Electronics'},
    {name: 'product 11', category: 'Watch'},
    {name: 'Nikon', category: 'Camera'},
    {name: 'LG', category: 'Electronics'},
    {name: 'Videocon', category: 'Electronics'},
    {name: 'product 15', category: 'Watch'},
]